### ISSUE TITLE
Error while setting up gtfs_rt platform for sensor

### ISSUE THREAD

**Issue by corneels** [mark1foley/ha-gtfs-rt-v2#15]
This issue started occurring quite recently, not sure if it is driven by updates to Home Assistant on my side or not. I updated to HA OS 10 quite recently.

I run HA on a Raspberry Pi.

Home Assistant 2023.4.5
Supervisor 2023.04.0
Operating System 10.0
Frontend 20230411.1 - latest

```
Logger: homeassistant.components.sensor
Source: custom_components/gtfs_rt/sensor.py:271
Integration: Sensor (documentation, issues)
First occurred: 09:41:50 (1 occurrences)
Last logged: 09:41:50

Error while setting up gtfs_rt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gtfs_rt/sensor.py", line 72, in setup_platform
    sensors.append(PublicTransportSensor(
  File "/config/custom_components/gtfs_rt/sensor.py", line 96, in __init__
    self.update()
  File "/config/custom_components/gtfs_rt/sensor.py", line 146, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/gtfs_rt/sensor.py", line 197, in update
    positions = self._get_vehicle_positions() if self._vehicle_position_url else {}
  File "/config/custom_components/gtfs_rt/sensor.py", line 271, in _get_vehicle_positions
    from google.transit import gtfs_realtime_pb2
  File "/usr/local/lib/python3.10/site-packages/google/transit/gtfs_realtime_pb2.py", line 50, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```

**Comment by mark1foley** [comment]
Hi,

Can you please provide your GTFS-RT setup from  the configuration.yaml file.

Thanks,

Mark

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Corneels de Waard ***@***.***>
Sent: Wednesday, April 19, 2023 9:46:48 AM
To: mark1foley/ha-gtfs-rt-v2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mark1foley/ha-gtfs-rt-v2] Error while setting up gtfs_rt platform for sensor (Issue #15)


This issue started occurring quite recently, not sure if it is driven by updates to Home Assistant on my side or not.

I run HA on a Raspberry Pi.

Logger: homeassistant.components.sensor
Source: custom_components/gtfs_rt/sensor.py:271
Integration: Sensor (documentation, issues)
First occurred: 09:41:50 (1 occurrences)
Last logged: 09:41:50

Error while setting up gtfs_rt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gtfs_rt/sensor.py", line 72, in setup_platform
    sensors.append(PublicTransportSensor(
  File "/config/custom_components/gtfs_rt/sensor.py", line 96, in __init__
    self.update()
  File "/config/custom_components/gtfs_rt/sensor.py", line 146, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/gtfs_rt/sensor.py", line 197, in update
    positions = self._get_vehicle_positions() if self._vehicle_position_url else {}
  File "/config/custom_components/gtfs_rt/sensor.py", line 271, in _get_vehicle_positions
    from google.transit import gtfs_realtime_pb2
  File "/usr/local/lib/python3.10/site-packages/google/transit/gtfs_realtime_pb2.py", line 50, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by corneels** [comment]
Has run flawlessly for several months prior to this week.

```
- platform: gtfs_rt
  trip_update_url: 'https://gtfsrt.api.translink.com.au/api/realtime/SEQ/TripUpdates'
  vehicle_position_url: 'https://gtfsrt.api.translink.com.au/api/realtime/SEQ/VehiclePositions'
  route_delimiter: '-'
  departures:
  - name: '1 9 9 Bus'
    route: 199
    stopid: 1136
    icon: mdi:bus
    service_type: Bus
  - name: '6 0 Bus'
    route: 60
    stopid: 1132
    icon: mdi:bus
    service_type: Bus
```

**Comment by vincegre** [comment]
Same problem here with some GTFS feeds in Switzerland that were working perfect before ! I have updated the API key just in case but no changes :( (HAOS on Nuc latest release).

**Comment by corneels** [comment]
Looks like this is a broader issue that is affecting other integrations, see home-assistant/core#91614

**Comment by mark1foley** [comment]
Hi All, 

As you have already worked out the version of protbuf has been upgraded in HA version 2023.4.5 which broke this and several other integrations.  Unfortunately it is still broken in 2023.4.6.  
I am working on solutions.  To be honest I am not the world's greatest programmer so any advice or suggestions would be gratefully received.

Mark

**Comment by corneels** [comment]
I am also at a bit of a loss, for debugging I used this [example code](https://github.com/MobilityData/gtfs-realtime-bindings/tree/master/python#example-code) with the latest version of gtfs-realtime-bindings (1.0.0) installed on my local machine:

```
import requests
from google.transit import gtfs_realtime_pb2

feed = gtfs_realtime_pb2.FeedMessage()
response = requests.get(
    "https://gtfsrt.api.translink.com.au/api/realtime/SEQ/TripUpdates"
)
feed.ParseFromString(response.content)
for entity in feed.entity:
    if entity.HasField("trip_update"):
        print(entity.trip_update)
```

It automatically installed its protobuf dependency, this is the output of `pipenv graph`:

```
black==23.3.0
  - click [required: >=8.0.0, installed: 8.1.3]
  - mypy-extensions [required: >=0.4.3, installed: 1.0.0]
  - packaging [required: >=22.0, installed: 23.1]
  - pathspec [required: >=0.9.0, installed: 0.11.1]
  - platformdirs [required: >=2, installed: 3.2.0]
gtfs-realtime-bindings==1.0.0
  - protobuf [required: Any, installed: 4.22.3]
  - setuptools [required: Any, installed: 67.7.1]
requests==2.28.2
  - certifi [required: >=2017.4.17, installed: 2022.12.7]
  - charset-normalizer [required: >=2,<4, installed: 3.1.0]
  - idna [required: >=2.5,<4, installed: 3.4]
  - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.15]
```

And the code ran fine.

Of course, the `_pb2.py` file in my virtual environment has just been generated as it is brand new.

**Comment by corneels** [comment]
@mark1foley, I see that you are specifying 'gtfs-realtime-bindings=0.0.5'.

Could bumping this to latest fix the issue?

**Comment by mark1foley** [comment]
Thanks @corneels!  works great in my environment so I have merged your changes created a new release

**Comment by christopherdopp** [comment]
Nice! I switched to the latest build of this repo from the zacs/ha-gtfs-rt repo and my gtfs feeds are now working again without any exceptions in the log file. Thank you!

**Comment by InTheDaylight14** [comment]
Still having this issue on the latest version. Here are the logs.

GTFS Realtime 20230701.05
Home Assistant 2023.4.2 
Supervisor 2023.04.1 
Operating System 9.5 
Frontend 20230406.1 - latest 

```
Logger: homeassistant.components.sensor
Source: custom_components/gtfs_rt/sensor.py:126
Integration: Sensor (documentation, issues)
First occurred: April 27, 2023 at 15:07:21 (1 occurrences)
Last logged: April 27, 2023 at 15:07:21

Error while setting up gtfs_rt platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gtfs-rt.itsmarta.com', port=443): Max retries exceeded with url: /TMGTFSRealTimeWebService/vehicle/vehiclepositions.pb (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gtfs_rt/sensor.py", line 108, in setup_platform
    PublicTransportSensor(
  File "/config/custom_components/gtfs_rt/sensor.py", line 155, in __init__
    self.update()
  File "/config/custom_components/gtfs_rt/sensor.py", line 221, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/gtfs_rt/sensor.py", line 297, in update
    self._get_vehicle_positions()
  File "/config/custom_components/gtfs_rt/sensor.py", line 429, in _get_vehicle_positions
    feed_entities = get_gtfs_feed_entities(
  File "/config/custom_components/gtfs_rt/sensor.py", line 126, in get_gtfs_feed_entities
    response = requests.get(url, headers=headers, timeout=20)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='gtfs-rt.itsmarta.com', port=443): Max retries exceeded with url: /TMGTFSRealTimeWebService/vehicle/vehiclepositions.pb (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
```

Config:
```
  - platform: gtfs_rt
    trip_update_url: 'https://gtfs-rt.itsmarta.com/TMGTFSRealTimeWebService/tripupdate/tripupdates.pb'
    vehicle_position_url: 'https://gtfs-rt.itsmarta.com/TMGTFSRealTimeWebService/vehicle/vehiclepositions.pb'
    departures:
    - name: Axxxx
      route: 1####
      stopid: 5####
    - name: Lxxxxx
      route: 1####
      stopid: 5####
    - name: Qxxxxx
      route: 1#### 
      stopid: 5####
```

**Comment by corneels** [comment]
Looking at your error it appears to be a different issue.
