### ISSUE TITLE
Error while setting up gtfs_rt platform for sensor

### ISSUE THREAD

**Issue by InTheDaylight14** [mark1foley/ha-gtfs-rt-v2#19]
Seems to be different than #15 so making a new issue. 

HA ran as a VM
GTFS Realtime 20230701.05
Home Assistant 2023.4.2 
Supervisor 2023.04.1 
Operating System 9.5 
Frontend 20230406.1 - latest 

```
Logger: homeassistant.components.sensor
Source: custom_components/gtfs_rt/sensor.py:126
Integration: Sensor (documentation, issues)
First occurred: April 27, 2023 at 15:07:21 (1 occurrences)
Last logged: April 27, 2023 at 15:07:21

Error while setting up gtfs_rt platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gtfs-rt.itsmarta.com', port=443): Max retries exceeded with url: /TMGTFSRealTimeWebService/vehicle/vehiclepositions.pb (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gtfs_rt/sensor.py", line 108, in setup_platform
    PublicTransportSensor(
  File "/config/custom_components/gtfs_rt/sensor.py", line 155, in __init__
    self.update()
  File "/config/custom_components/gtfs_rt/sensor.py", line 221, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/gtfs_rt/sensor.py", line 297, in update
    self._get_vehicle_positions()
  File "/config/custom_components/gtfs_rt/sensor.py", line 429, in _get_vehicle_positions
    feed_entities = get_gtfs_feed_entities(
  File "/config/custom_components/gtfs_rt/sensor.py", line 126, in get_gtfs_feed_entities
    response = requests.get(url, headers=headers, timeout=20)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='gtfs-rt.itsmarta.com', port=443): Max retries exceeded with url: /TMGTFSRealTimeWebService/vehicle/vehiclepositions.pb (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
```

Config:
```
  - platform: gtfs_rt
    trip_update_url: 'https://gtfs-rt.itsmarta.com/TMGTFSRealTimeWebService/tripupdate/tripupdates.pb'
    vehicle_position_url: 'https://gtfs-rt.itsmarta.com/TMGTFSRealTimeWebService/vehicle/vehiclepositions.pb'
    departures:
    - name: Axxxx
      route: 1####
      stopid: 5####
    - name: Lxxxxx
      route: 1####
      stopid: 5####
    - name: Qxxxxx
      route: 1#### 
      stopid: 5####
```

**Comment by mark1foley** [comment]
Hi, I've done a bit of testing on this and now know more about SSL certs than I used to.  Firstly, I used a browser on my Win10 box to manually download the protbuf file from [https://gtfs-rt.itsmarta.com/TMGTFSRealTimeWebService/tripupdate/tripupdates.pb](url).  I was then able to decode the file and it is valid so no problems there.  

However, this leaves us with the situation when a browser can connect to [https://gtfs-rt.itsmarta.com](url) without error but python fails with an SSL error validating the certificate when connecting to the exact same URL.  This rules out problems like expired certificates (because the browser would have reported it).  So it was a bit confusing!

As it turns out Python uses it's own cert store installed by a package called certifi.  So I thought maybe the root cert was missing from the store but this was not the case.  Also, my local GTFS RT provider (translink.com.au) happens to use the same root cert and the integration works fine.  So I figured that it was something to do with the intermediate certificates.

The certs used by the site have the following structure:
  DigiCert Global Root CA <- root cert
     DigiCert Global G2 TLS RSA SHA256 2020 CA1 <- intermediate cert
        gtfs-rt.itsmarta.com <- server cert

Apparently, browsers use a thing called "AIA chasing" to resolve problems when details of intermediate certificates are not published correctly but python does not do this (see [https://bugs.python.org/issue18617#msg293894](url) for more details).  There is a website ([https://www.ssllabs.com/ssltest/index.html](url)) that can be used to test issues with intermediate certs.  If I used this to test the url for my local URL provider ([gtfsrt.api.translink.com.au](url)) so errors are reported with the intermediate certificate.  But is I test the Marta URL ([gtfs-rt.itsmarta.com](url)) it reports certificate chaining issues.  This is what I believe is causing the error.

There is a library available ([https://pypi.org/project/aia/](url)) to work around the issue which I am happy to look at using.  But I'm sure at this point if it is even available in HA.  

In the mean time I suggest that you contact Marta and ask them to correct the certificate chaining issues.

Regards,

Mark

**Comment by InTheDaylight14** [comment]
MARTA fixed their intermediate certificate! I was able to get this integration working with them. Thanks for the help looking into this issue.
