### ISSUE TITLE
vehicle_position_url is not optional since updating to 20230701.05

### ISSUE THREAD

**Issue by AJCinMD** [mark1foley/ha-gtfs-rt-v2#20]
My configuration was working fine without specifying the "vehicle_position_url" prior to updating HA to 2023.4.4. I had to upgrade to version 20230701.05 in order to resolve the protobuf problem in issue #15 after upgrading HA. Since the upgrade, I keep receiving errors in the log as follows: 

Error while setting up gtfs_rt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gtfs_rt/sensor.py", line 108, in setup_platform
    PublicTransportSensor(
  File "/config/custom_components/gtfs_rt/sensor.py", line 155, in __init__
    self.update()
  File "/config/custom_components/gtfs_rt/sensor.py", line 221, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/gtfs_rt/sensor.py", line 297, in update
    self._get_vehicle_positions()
  File "/config/custom_components/gtfs_rt/sensor.py", line 429, in _get_vehicle_positions
    feed_entities = get_gtfs_feed_entities(
  File "/config/custom_components/gtfs_rt/sensor.py", line 126, in get_gtfs_feed_entities
    response = requests.get(url, headers=headers, timeout=20)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

The error goes away if I provide a value for vehicle_position_url but this is undesirable as the particular feed that I'm using has multiple vehicles but gtfs-rt is only showing one of the positions w/o a train ID which is worthless to me so I'd rather not have it at all. I've tried setting the value to "https://None" as suggested above but that just makes the sensor not work either.

For reference, the config that I'm using is:

sensor:
  - platform: gtfs_rt
    trip_update_url: 'https://mdotmta-gtfs-rt.s3.amazonaws.com/MARC+RT/marc-tu.pb'
    departures:
      - name: "MARC Northbound - Washington, D.C."
        route: 11705
        stopid: 11958
        icon: mdi:train
        service_type: Train

**Comment by mark1foley** [comment]
Please try adding the following:
vehicle_position_url: ''

**Comment by AJCinMD** [comment]
Setting vehicle_position_url: '' seems to resolve the issue. It wasn't required prior to version 20230701.05 though. Perhaps a check to see if it's defined and setting it to an empty string if not would negate the need for specifying a blank value in configuration.yaml? Btw, thanks a lot for your work on maintaining this integration!

**Comment by mark1foley** [comment]
Thanks for letting me know.  Yes, the behaviour has changed inadvertently due to a cleanup of the code that was done so apologies for that.  I can see what the issue is and will fix up in the next version.
