### ISSUE TITLE
No module named 'google.transit' since 2024.12

### ISSUE THREAD

**Issue by mguaylam** [mark1foley/ha-gtfs-rt-v2#43]
Since updating to HA 2024.12 the component can't find the dependency for the bindings anymore :
```PYTHON
Enregistreur: homeassistant.config
Source: config.py:1055
S'est produit pour la première fois: 17:42:53 (1 occurrences)
Dernier enregistrement: 17:42:53

Platform error: sensor - No module named 'google.transit'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1055, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1107, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1154, in async_get_platforms
    await self.hass.async_add_import_executor_job(
        self._load_platforms, platform_names
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1097, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1271, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1303, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/gtfs_rt/sensor.py", line 8, in <module>
    from google.transit import gtfs_realtime_pb2
ModuleNotFoundError: No module named 'google.transit'
```

**Comment by mguaylam** [comment]
Installing it manually does work :
```BASH
# pip3 install gtfs-realtime-bindings
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting gtfs-realtime-bindings
  Downloading gtfs-realtime-bindings-1.0.0.tar.gz (6.2 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/site-packages (from gtfs-realtime-bindings) (75.6.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/site-packages (from gtfs-realtime-bindings) (5.28.3)
Building wheels for collected packages: gtfs-realtime-bindings
  Building wheel for gtfs-realtime-bindings (setup.py) ... done
  Created wheel for gtfs-realtime-bindings: filename=gtfs_realtime_bindings-1.0.0-py3-none-any.whl size=5984 sha256=14bb15f10c5307aa2c3c1f605f59702f9d77f918a4a3f2ea89c57683473b8b7e
  Stored in directory: /tmp/pip-ephem-wheel-cache-2gkntzsa/wheels/7c/c1/b0/b839d88a76f54c82086b98ebcb3ad52cdd3e0c33a3f32d28a8
Successfully built gtfs-realtime-bindings
Installing collected packages: gtfs-realtime-bindings
Successfully installed gtfs-realtime-bindings-1.0.0
```

**Comment by mark1foley** [comment]
Hi, I had no issues when I updated to 2024.12.1 so I'm not sure why the GTFS realtime bindings module would have disappeared for you.  Seems like you are running a running a system using one of the more advanced installation methods and/or a different language so maybe it was something to do with that.

**Comment by mguaylam** [comment]
I'm using Podman (docker). It's indeed more involved but should not bother too much from my understanding. I see you are at `2024.12.1` i'm at `2024.12.3` perhaps it's with `.3`?

I tried simulating the dependency install with the constraints from HA but it did pass. It's weird.

It's installing with `--quiet` it's annoying to debug :
```Python
2024-12-15 18:21:07.819 DEBUG (SyncWorker_3) [homeassistant.util.package] Running uv pip command: args=['/usr/local/bin/python3', '-m', 'uv', 'pip', 'install', '--quiet', 'gtfs-realtime-bindings==1.0.0', '--index-strategy', 'unsafe-first-match', '--upgrade', '--constraint', '/usr/src/homeassistant/homeassistant/package_constraints.txt', '--target', '/config/deps']
```

**Comment by mark1foley** [comment]
Ok, I'll upgrade to 2024.12.3 today and see if I have any issues.   Do you install any of the previous 2024.12.x versions or go straight to 2024.12.3?

**Comment by mguaylam** [comment]
I went straight from `2024.11.X` to `2024.12.3`.

**Comment by mguaylam** [comment]
Just tried `2024.12.1` and it's also an issue for me. I can see the dependency being installed on the file system so i'm not sure why it's not finding it. Maybe to test it you would need to delete the dependency before.

**Comment by mark1foley** [comment]
Hi, I upgraded mine to 2024.12.3 and it works fine.  Sorry, I can't support every way that someone chooses to install home assistant.  Honestly, if you choose to use a non-standard installation option then you take on the responsibility to resolve issues like this.

**Comment by mguaylam** [comment]
While chatting with Tinkerer, he made me aware of this [known issue](https://github.com/home-assistant/core/issues/127966) also followed [here](https://community.home-assistant.io/t/wth-is-going-on-with-docker-container-installs-and-third-party-integrations-that-need-python-modules/806430) for the month of WTH.

It's due to [Home-Assistant migrating to UV](https://github.com/home-assistant/core/pull/132404#issuecomment-2528951231) which breaks the detection of containerized environment in a OCI context and affect package management. Docker is officially supported but the OCI environment broke when migrating to UV at 2024.10.X. So indeed not an issue with this project but people might hit this wall if they run anything else then Docker for containerization such as Kubernetes, Podman, etc.

Thank you for the time you spent looking at it. It's appreciated.
