### ISSUE TITLE
Unable to get it working with Swiss Transport :(

### ISSUE THREAD

**Issue by vincegre** [mark1foley/ha-gtfs-rt-v2#5]
Hi

I'm trying to use your integration with swiss transport but it generates some errors in log at startup:

```
Logger: homeassistant.components.sensor
Source: custom_components/gtfs_rt/sensor.py:203
Integration: Capteur ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 12:07:01 (1 occurrences)
Last logged: 12:07:01

Error while setting up gtfs_rt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gtfs_rt/sensor.py", line 66, in setup_platform
    sensors.append(PublicTransportSensor(
  File "/config/custom_components/gtfs_rt/sensor.py", line 88, in __init__
    self.update()
  File "/config/custom_components/gtfs_rt/sensor.py", line 137, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/gtfs_rt/sensor.py", line 186, in update
    self._update_route_statuses(positions)
  File "/config/custom_components/gtfs_rt/sensor.py", line 203, in _update_route_statuses
    feed.ParseFromString(response.content)
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/message.py", line 202, in ParseFromString
    return self.MergeFromString(serialized)
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 1128, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 1178, in InternalParse
    raise message_mod.DecodeError('Field number 0 is illegal.')
google.protobuf.message.DecodeError: Field number 0 is illegal.
```
Configuration in HA:

```
sensor:
  - platform: gtfs_rt
    trip_update_url: 'https://opentransportdata.swiss/de/dataset/timetable-2022-gtfs2020/permalink'
    departures:
    - name: "6 vers Maladiere"
      route: 10.006
      stopid: 8579238
      icon: mdi:bus
```

I get that error in logs:

```
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.gtfs_rt.sensor
Source: custom_components/gtfs_rt/sensor.py:66
Integration: gtfs_rt (documentation, issues)
First occurred: 12:20:43 (1 occurrences)
Last logged: 12:20:43

updating trip data got 401:b'{\n "error": "Authorization field missing"\n}'
```

No support of API key ? as swiss transport needs it !

Thanks

Vincèn

**Comment by mark1foley** [comment]
Hi,
Apologies for the delayed response but I have been on holidays.

As per the documentation (https://github.com/mark1foley/ha-gtfs-rt-v2#readme), api_key is an optional configuration variable.  Add it after trip_update_url and before departures

Regards,
Mark
